---
# tasks file for kvm_install_new_vm

- name: Generate qcow2 storage file
  ansible.builtin.command: |
    qemu-img create \
    -f qcow2 \
    {{ kvm_provision_libvirt_pool_dir }}/{{ kvm_provision_vm_name }}.qcow2 \
    {{ kvm_provision_vm_size_of_storage }} \
  register: storage_result
  changed_when: storage_result.rc == 0

- name: Ensure 0600 mode to qcow2 file
  ansible.builtin.file:
    path: "{{ kvm_provision_libvirt_pool_dir }}/{{ kvm_provision_vm_name }}.qcow2"
    mode: '0600'

- name: Install VM
  when: image.dest is defined and storage_result is changed
  ansible.builtin.command: |
    virt-install \
    --name={{ kvm_provision_vm_name }} \
    --vcpus={{ kvm_provision_vm_vcpus }} \
    --ram={{ kvm_provision_vm_ram_mb }} \
    --network={{ kvm_provision_vm_net }} \
    --os-variant={{ kvm_provision_vm_os_variant }} \
    --graphics={{ kvm_provision_vm_graphics }} \
    {{ kvm_provision_virt_install_extra_args }} \
    --cdrom={{ image.dest }} \
    --disk path={{ kvm_provision_libvirt_pool_dir }}/{{ kvm_provision_vm_name }}.qcow2,format=qcow2 \
    --noautoconsole \
  register: conf_image_result
  changed_when: conf_image_result.rc == 0
